#set the title, description, and minima theme
title: "Kyle Prather"
description: "Courses, Research, Builds, and Essays"
theme: minima  # You can start with Minima or switch later

#set the sidebar layout
remote_theme: pmarsceill/just-the-docs

#hopefully resolve weird newline bug
kramdown:
  parse_block_html: true
  hard_wrap: false
  input: GFM
